package dev.gaurav.notification.application.port;

import dev.gaurav.notification.application.command.SendNotificationCommand;
import dev.gaurav.notification.domain.enums.Channel;

import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * The single atomic accept decision: {@code notification_request} + one {@code notification} per
 * channel + one {@code outbox_message}, in one transaction.
 *
 * <p><strong>The transaction boundary is this method.</strong> It is one method rather than three
 * so that no caller can compose a partial accept — writing the rows and the outbox entry separately
 * is a dual write, and a crash between them either loses the message or, worse, publishes work for
 * a row that was rolled back. The implementing adapter is annotated {@code @Transactional}; there
 * is no partial success to handle here, which is why {@link #persist} has no failure enum.
 *
 * <p>The outbox row is what makes the Kafka publish optional. It is inserted in the same
 * transaction as the notification, so "accepted" and "will be published" become the same fact, and
 * the sweeper turns a lost publish into a ~2 s delay instead of a lost message.
 *
 * <p>Recipients are deliberately <em>not</em> expanded here. A 10M-recipient campaign has to answer
 * inside the 250 ms budget, so the audience reference is stored and the fan-out happens
 * asynchronously — the Claim Check pattern.
 */
public interface AcceptanceWriter {

    /**
     * @param requestId  generated by the caller, not the database, so it can appear in the response
     *                   and in the outbox payload without a round trip
     * @param acceptedAt the row's {@code created_at}, and therefore its partition. Passed in so the
     *                   whole accept uses one timestamp: letting each insert call {@code now()}
     *                   can straddle midnight and scatter one request across two daily partitions
     * @param expiresAt  the hard TTL, from {@link SendNotificationCommand#expiresAt(Instant)}
     */
    AcceptedRecords persist(
            SendNotificationCommand command, UUID requestId, Instant acceptedAt, Instant expiresAt);

    /**
     * The ids the transaction created.
     *
     * @param requestCreatedAt echoed back because it is the partition key: every later read or
     *                         status write that carries it prunes to one daily partition instead of
     *                         scanning all of them
     */
    record AcceptedRecords(
            UUID requestId,
            Instant requestCreatedAt,
            List<PersistedNotification> notifications,
            int recipientCount) {

        public AcceptedRecords {
            Objects.requireNonNull(requestId, "requestId");
            Objects.requireNonNull(requestCreatedAt, "requestCreatedAt");
            notifications = notifications == null ? List.of() : List.copyOf(notifications);
            if (notifications.isEmpty()) {
                throw new IllegalArgumentException(
                        "an accept transaction that created no notification committed nothing to send");
            }
        }
    }

    /** @param createdAt the notification's partition key, carried for the same reason as above */
    record PersistedNotification(UUID id, Instant createdAt, Channel channel) {

        public PersistedNotification {
            Objects.requireNonNull(id, "id");
            Objects.requireNonNull(createdAt, "createdAt");
            Objects.requireNonNull(channel, "channel");
        }
    }
}
